#pragma once

enum DataType {
	CONST_ERROR = -1,
	CONST_INT = 0,
	CONST_LONG = 1,
	CONST_FLOAT = 2,
	CONST_DOUBLE = 3,
	CONST_POINT = 4,
	CONST_POLYGON = 5,
	CONST_STRING = 6,
	CONST_BOOLEAN = 7,
	REG = 8,
	COLUMN_INT = 9,
	COLUMN_LONG = 10,
	COLUMN_FLOAT = 11,
	COLUMN_DOUBLE = 12,
	COLUMN_POINT = 13,
	COLUMN_POLYGON = 14,
	COLUMN_STRING = 15,
	COLUMN_BOOL = 16,
};