#include "GpuSqlDispatcherDateFunctions.h"
#include <array>

std::array<GpuSqlDispatcher::DispatchFunction, DataType::DATA_TYPE_SIZE> GpuSqlDispatcher::yearFunctions_ = {
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, int32_t>,
    &GpuSqlDispatcher::DateExtractConst<DateOperations::year>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::year, int8_t>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, int32_t>,
    &GpuSqlDispatcher::DateExtractCol<DateOperations::year>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::year, int8_t>};
std::array<GpuSqlDispatcher::DispatchFunction, DataType::DATA_TYPE_SIZE> GpuSqlDispatcher::monthFunctions_ = {
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, int32_t>,
    &GpuSqlDispatcher::DateExtractConst<DateOperations::month>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::month, int8_t>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, int32_t>,
    &GpuSqlDispatcher::DateExtractCol<DateOperations::month>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::month, int8_t>};
std::array<GpuSqlDispatcher::DispatchFunction, DataType::DATA_TYPE_SIZE> GpuSqlDispatcher::dayFunctions_ = {
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, int32_t>,
    &GpuSqlDispatcher::DateExtractConst<DateOperations::day>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::day, int8_t>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, int32_t>,
    &GpuSqlDispatcher::DateExtractCol<DateOperations::day>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::day, int8_t>};
std::array<GpuSqlDispatcher::DispatchFunction, DataType::DATA_TYPE_SIZE> GpuSqlDispatcher::hourFunctions_ = {
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, int32_t>,
    &GpuSqlDispatcher::DateExtractConst<DateOperations::hour>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::hour, int8_t>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, int32_t>,
    &GpuSqlDispatcher::DateExtractCol<DateOperations::hour>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::hour, int8_t>};
std::array<GpuSqlDispatcher::DispatchFunction, DataType::DATA_TYPE_SIZE> GpuSqlDispatcher::minuteFunctions_ = {
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, int32_t>,
    &GpuSqlDispatcher::DateExtractConst<DateOperations::minute>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::minute, int8_t>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, int32_t>,
    &GpuSqlDispatcher::DateExtractCol<DateOperations::minute>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::minute, int8_t>};
std::array<GpuSqlDispatcher::DispatchFunction, DataType::DATA_TYPE_SIZE> GpuSqlDispatcher::secondFunctions_ = {
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, int32_t>,
    &GpuSqlDispatcher::DateExtractConst<DateOperations::second>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerConst<DateOperations::second, int8_t>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, int32_t>,
    &GpuSqlDispatcher::DateExtractCol<DateOperations::second>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, float>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, double>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, ColmnarDB::Types::Point>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, ColmnarDB::Types::ComplexPolygon>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, std::string>,
    &GpuSqlDispatcher::InvalidOperandTypesErrorHandlerCol<DateOperations::second, int8_t>};
