// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/InfoMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2fInfoMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2fInfoMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2fInfoMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2fInfoMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2fInfoMessage_2eproto;
namespace ColmnarDB {
namespace NetworkClient {
namespace Message {
class InfoMessage;
class InfoMessageDefaultTypeInternal;
extern InfoMessageDefaultTypeInternal _InfoMessage_default_instance_;
}  // namespace Message
}  // namespace NetworkClient
}  // namespace ColmnarDB
PROTOBUF_NAMESPACE_OPEN
template<> ::ColmnarDB::NetworkClient::Message::InfoMessage* Arena::CreateMaybeMessage<::ColmnarDB::NetworkClient::Message::InfoMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ColmnarDB {
namespace NetworkClient {
namespace Message {

enum InfoMessage_StatusCode : int {
  InfoMessage_StatusCode_OK = 0,
  InfoMessage_StatusCode_WAIT = 1,
  InfoMessage_StatusCode_GET_NEXT_RESULT = 6,
  InfoMessage_StatusCode_QUERY_ERROR = 2,
  InfoMessage_StatusCode_IMPORT_ERROR = 3,
  InfoMessage_StatusCode_CONN_ESTABLISH = 4,
  InfoMessage_StatusCode_CONN_END = 5,
  InfoMessage_StatusCode_HEARTBEAT = 7,
  InfoMessage_StatusCode_InfoMessage_StatusCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  InfoMessage_StatusCode_InfoMessage_StatusCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool InfoMessage_StatusCode_IsValid(int value);
constexpr InfoMessage_StatusCode InfoMessage_StatusCode_StatusCode_MIN = InfoMessage_StatusCode_OK;
constexpr InfoMessage_StatusCode InfoMessage_StatusCode_StatusCode_MAX = InfoMessage_StatusCode_HEARTBEAT;
constexpr int InfoMessage_StatusCode_StatusCode_ARRAYSIZE = InfoMessage_StatusCode_StatusCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* InfoMessage_StatusCode_descriptor();
template<typename T>
inline const std::string& InfoMessage_StatusCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, InfoMessage_StatusCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function InfoMessage_StatusCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    InfoMessage_StatusCode_descriptor(), enum_t_value);
}
inline bool InfoMessage_StatusCode_Parse(
    const std::string& name, InfoMessage_StatusCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<InfoMessage_StatusCode>(
    InfoMessage_StatusCode_descriptor(), name, value);
}
// ===================================================================

class InfoMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ColmnarDB.NetworkClient.Message.InfoMessage) */ {
 public:
  InfoMessage();
  virtual ~InfoMessage();

  InfoMessage(const InfoMessage& from);
  InfoMessage(InfoMessage&& from) noexcept
    : InfoMessage() {
    *this = ::std::move(from);
  }

  inline InfoMessage& operator=(const InfoMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline InfoMessage& operator=(InfoMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InfoMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InfoMessage* internal_default_instance() {
    return reinterpret_cast<const InfoMessage*>(
               &_InfoMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InfoMessage& a, InfoMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(InfoMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InfoMessage* New() const final {
    return CreateMaybeMessage<InfoMessage>(nullptr);
  }

  InfoMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InfoMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InfoMessage& from);
  void MergeFrom(const InfoMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InfoMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ColmnarDB.NetworkClient.Message.InfoMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_messages_2fInfoMessage_2eproto);
    return ::descriptor_table_messages_2fInfoMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef InfoMessage_StatusCode StatusCode;
  static constexpr StatusCode OK =
    InfoMessage_StatusCode_OK;
  static constexpr StatusCode WAIT =
    InfoMessage_StatusCode_WAIT;
  static constexpr StatusCode GET_NEXT_RESULT =
    InfoMessage_StatusCode_GET_NEXT_RESULT;
  static constexpr StatusCode QUERY_ERROR =
    InfoMessage_StatusCode_QUERY_ERROR;
  static constexpr StatusCode IMPORT_ERROR =
    InfoMessage_StatusCode_IMPORT_ERROR;
  static constexpr StatusCode CONN_ESTABLISH =
    InfoMessage_StatusCode_CONN_ESTABLISH;
  static constexpr StatusCode CONN_END =
    InfoMessage_StatusCode_CONN_END;
  static constexpr StatusCode HEARTBEAT =
    InfoMessage_StatusCode_HEARTBEAT;
  static inline bool StatusCode_IsValid(int value) {
    return InfoMessage_StatusCode_IsValid(value);
  }
  static constexpr StatusCode StatusCode_MIN =
    InfoMessage_StatusCode_StatusCode_MIN;
  static constexpr StatusCode StatusCode_MAX =
    InfoMessage_StatusCode_StatusCode_MAX;
  static constexpr int StatusCode_ARRAYSIZE =
    InfoMessage_StatusCode_StatusCode_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  StatusCode_descriptor() {
    return InfoMessage_StatusCode_descriptor();
  }
  template<typename T>
  static inline const std::string& StatusCode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, StatusCode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function StatusCode_Name.");
    return InfoMessage_StatusCode_Name(enum_t_value);
  }
  static inline bool StatusCode_Parse(const std::string& name,
      StatusCode* value) {
    return InfoMessage_StatusCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string Message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .ColmnarDB.NetworkClient.Message.InfoMessage.StatusCode Code = 1;
  void clear_code();
  ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode code() const;
  void set_code(::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode value);
  private:
  ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode _internal_code() const;
  void _internal_set_code(::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode value);
  public:

  // @@protoc_insertion_point(class_scope:ColmnarDB.NetworkClient.Message.InfoMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  int code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_messages_2fInfoMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InfoMessage

// .ColmnarDB.NetworkClient.Message.InfoMessage.StatusCode Code = 1;
inline void InfoMessage::clear_code() {
  code_ = 0;
}
inline ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode InfoMessage::_internal_code() const {
  return static_cast< ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode >(code_);
}
inline ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode InfoMessage::code() const {
  // @@protoc_insertion_point(field_get:ColmnarDB.NetworkClient.Message.InfoMessage.Code)
  return _internal_code();
}
inline void InfoMessage::_internal_set_code(::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode value) {
  
  code_ = value;
}
inline void InfoMessage::set_code(::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:ColmnarDB.NetworkClient.Message.InfoMessage.Code)
}

// string Message = 2;
inline void InfoMessage::clear_message() {
  message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& InfoMessage::message() const {
  // @@protoc_insertion_point(field_get:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
  return _internal_message();
}
inline void InfoMessage::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
}
inline std::string* InfoMessage::mutable_message() {
  // @@protoc_insertion_point(field_mutable:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
  return _internal_mutable_message();
}
inline const std::string& InfoMessage::_internal_message() const {
  return message_.GetNoArena();
}
inline void InfoMessage::_internal_set_message(const std::string& value) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void InfoMessage::set_message(std::string&& value) {
  
  message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
}
inline void InfoMessage::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
}
inline void InfoMessage::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
}
inline std::string* InfoMessage::_internal_mutable_message() {
  
  return message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* InfoMessage::release_message() {
  // @@protoc_insertion_point(field_release:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
  
  return message_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void InfoMessage::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:ColmnarDB.NetworkClient.Message.InfoMessage.Message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Message
}  // namespace NetworkClient
}  // namespace ColmnarDB

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode>() {
  return ::ColmnarDB::NetworkClient::Message::InfoMessage_StatusCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2fInfoMessage_2eproto
