// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages/SetDatabaseMessage.proto

#include "SetDatabaseMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace ColmnarDB {
namespace NetworkClient {
namespace Message {
class SetDatabaseMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetDatabaseMessage>
      _instance;
} _SetDatabaseMessage_default_instance_;
}  // namespace Message
}  // namespace NetworkClient
}  // namespace ColmnarDB
namespace protobuf_messages_2fSetDatabaseMessage_2eproto {
static void InitDefaultsSetDatabaseMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ColmnarDB::NetworkClient::Message::_SetDatabaseMessage_default_instance_;
    new (ptr) ::ColmnarDB::NetworkClient::Message::SetDatabaseMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ColmnarDB::NetworkClient::Message::SetDatabaseMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SetDatabaseMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSetDatabaseMessage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SetDatabaseMessage.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ColmnarDB::NetworkClient::Message::SetDatabaseMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ColmnarDB::NetworkClient::Message::SetDatabaseMessage, databasename_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ColmnarDB::NetworkClient::Message::SetDatabaseMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ColmnarDB::NetworkClient::Message::_SetDatabaseMessage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "messages/SetDatabaseMessage.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n!messages/SetDatabaseMessage.proto\022\037Col"
      "mnarDB.NetworkClient.Message\"*\n\022SetDatab"
      "aseMessage\022\024\n\014DatabaseName\030\001 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messages/SetDatabaseMessage.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_messages_2fSetDatabaseMessage_2eproto
namespace ColmnarDB {
namespace NetworkClient {
namespace Message {

// ===================================================================

void SetDatabaseMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetDatabaseMessage::kDatabaseNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetDatabaseMessage::SetDatabaseMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_messages_2fSetDatabaseMessage_2eproto::scc_info_SetDatabaseMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
}
SetDatabaseMessage::SetDatabaseMessage(const SetDatabaseMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  databasename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.databasename().size() > 0) {
    databasename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.databasename_);
  }
  // @@protoc_insertion_point(copy_constructor:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
}

void SetDatabaseMessage::SharedCtor() {
  databasename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SetDatabaseMessage::~SetDatabaseMessage() {
  // @@protoc_insertion_point(destructor:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  SharedDtor();
}

void SetDatabaseMessage::SharedDtor() {
  databasename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SetDatabaseMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SetDatabaseMessage::descriptor() {
  ::protobuf_messages_2fSetDatabaseMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messages_2fSetDatabaseMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetDatabaseMessage& SetDatabaseMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_messages_2fSetDatabaseMessage_2eproto::scc_info_SetDatabaseMessage.base);
  return *internal_default_instance();
}


void SetDatabaseMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  databasename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool SetDatabaseMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string DatabaseName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_databasename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->databasename().data(), static_cast<int>(this->databasename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ColmnarDB.NetworkClient.Message.SetDatabaseMessage.DatabaseName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  return false;
#undef DO_
}

void SetDatabaseMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string DatabaseName = 1;
  if (this->databasename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->databasename().data(), static_cast<int>(this->databasename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ColmnarDB.NetworkClient.Message.SetDatabaseMessage.DatabaseName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->databasename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
}

::google::protobuf::uint8* SetDatabaseMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string DatabaseName = 1;
  if (this->databasename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->databasename().data(), static_cast<int>(this->databasename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ColmnarDB.NetworkClient.Message.SetDatabaseMessage.DatabaseName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->databasename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  return target;
}

size_t SetDatabaseMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string DatabaseName = 1;
  if (this->databasename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->databasename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SetDatabaseMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const SetDatabaseMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetDatabaseMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
    MergeFrom(*source);
  }
}

void SetDatabaseMessage::MergeFrom(const SetDatabaseMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.databasename().size() > 0) {

    databasename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.databasename_);
  }
}

void SetDatabaseMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetDatabaseMessage::CopyFrom(const SetDatabaseMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ColmnarDB.NetworkClient.Message.SetDatabaseMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetDatabaseMessage::IsInitialized() const {
  return true;
}

void SetDatabaseMessage::Swap(SetDatabaseMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SetDatabaseMessage::InternalSwap(SetDatabaseMessage* other) {
  using std::swap;
  databasename_.Swap(&other->databasename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SetDatabaseMessage::GetMetadata() const {
  protobuf_messages_2fSetDatabaseMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messages_2fSetDatabaseMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Message
}  // namespace NetworkClient
}  // namespace ColmnarDB
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ColmnarDB::NetworkClient::Message::SetDatabaseMessage* Arena::CreateMaybeMessage< ::ColmnarDB::NetworkClient::Message::SetDatabaseMessage >(Arena* arena) {
  return Arena::CreateInternal< ::ColmnarDB::NetworkClient::Message::SetDatabaseMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
