// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types/ComplexPolygon.proto

#ifndef PROTOBUF_INCLUDED_Types_2fComplexPolygon_2eproto
#define PROTOBUF_INCLUDED_Types_2fComplexPolygon_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Types_2fComplexPolygon_2eproto 

namespace protobuf_Types_2fComplexPolygon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Types_2fComplexPolygon_2eproto
namespace ColmnarDB {
namespace Types {
class ComplexPolygon;
class ComplexPolygonDefaultTypeInternal;
extern ComplexPolygonDefaultTypeInternal _ComplexPolygon_default_instance_;
class GeoPoint;
class GeoPointDefaultTypeInternal;
extern GeoPointDefaultTypeInternal _GeoPoint_default_instance_;
class Polygon;
class PolygonDefaultTypeInternal;
extern PolygonDefaultTypeInternal _Polygon_default_instance_;
}  // namespace Types
}  // namespace ColmnarDB
namespace google {
namespace protobuf {
template<> ::ColmnarDB::Types::ComplexPolygon* Arena::CreateMaybeMessage<::ColmnarDB::Types::ComplexPolygon>(Arena*);
template<> ::ColmnarDB::Types::GeoPoint* Arena::CreateMaybeMessage<::ColmnarDB::Types::GeoPoint>(Arena*);
template<> ::ColmnarDB::Types::Polygon* Arena::CreateMaybeMessage<::ColmnarDB::Types::Polygon>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ColmnarDB {
namespace Types {

// ===================================================================

class ComplexPolygon : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ColmnarDB.Types.ComplexPolygon) */ {
 public:
  ComplexPolygon();
  virtual ~ComplexPolygon();

  ComplexPolygon(const ComplexPolygon& from);

  inline ComplexPolygon& operator=(const ComplexPolygon& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ComplexPolygon(ComplexPolygon&& from) noexcept
    : ComplexPolygon() {
    *this = ::std::move(from);
  }

  inline ComplexPolygon& operator=(ComplexPolygon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ComplexPolygon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComplexPolygon* internal_default_instance() {
    return reinterpret_cast<const ComplexPolygon*>(
               &_ComplexPolygon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ComplexPolygon* other);
  friend void swap(ComplexPolygon& a, ComplexPolygon& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComplexPolygon* New() const final {
    return CreateMaybeMessage<ComplexPolygon>(NULL);
  }

  ComplexPolygon* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ComplexPolygon>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ComplexPolygon& from);
  void MergeFrom(const ComplexPolygon& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComplexPolygon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ColmnarDB.Types.Polygon polygons = 1;
  int polygons_size() const;
  void clear_polygons();
  static const int kPolygonsFieldNumber = 1;
  ::ColmnarDB::Types::Polygon* mutable_polygons(int index);
  ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::Polygon >*
      mutable_polygons();
  const ::ColmnarDB::Types::Polygon& polygons(int index) const;
  ::ColmnarDB::Types::Polygon* add_polygons();
  const ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::Polygon >&
      polygons() const;

  // @@protoc_insertion_point(class_scope:ColmnarDB.Types.ComplexPolygon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::Polygon > polygons_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Types_2fComplexPolygon_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Polygon : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ColmnarDB.Types.Polygon) */ {
 public:
  Polygon();
  virtual ~Polygon();

  Polygon(const Polygon& from);

  inline Polygon& operator=(const Polygon& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Polygon(Polygon&& from) noexcept
    : Polygon() {
    *this = ::std::move(from);
  }

  inline Polygon& operator=(Polygon&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Polygon& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Polygon* internal_default_instance() {
    return reinterpret_cast<const Polygon*>(
               &_Polygon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Polygon* other);
  friend void swap(Polygon& a, Polygon& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Polygon* New() const final {
    return CreateMaybeMessage<Polygon>(NULL);
  }

  Polygon* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Polygon>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Polygon& from);
  void MergeFrom(const Polygon& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Polygon* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ColmnarDB.Types.GeoPoint geoPoints = 1;
  int geopoints_size() const;
  void clear_geopoints();
  static const int kGeoPointsFieldNumber = 1;
  ::ColmnarDB::Types::GeoPoint* mutable_geopoints(int index);
  ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::GeoPoint >*
      mutable_geopoints();
  const ::ColmnarDB::Types::GeoPoint& geopoints(int index) const;
  ::ColmnarDB::Types::GeoPoint* add_geopoints();
  const ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::GeoPoint >&
      geopoints() const;

  // @@protoc_insertion_point(class_scope:ColmnarDB.Types.Polygon)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::GeoPoint > geopoints_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Types_2fComplexPolygon_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GeoPoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ColmnarDB.Types.GeoPoint) */ {
 public:
  GeoPoint();
  virtual ~GeoPoint();

  GeoPoint(const GeoPoint& from);

  inline GeoPoint& operator=(const GeoPoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GeoPoint(GeoPoint&& from) noexcept
    : GeoPoint() {
    *this = ::std::move(from);
  }

  inline GeoPoint& operator=(GeoPoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GeoPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeoPoint* internal_default_instance() {
    return reinterpret_cast<const GeoPoint*>(
               &_GeoPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GeoPoint* other);
  friend void swap(GeoPoint& a, GeoPoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GeoPoint* New() const final {
    return CreateMaybeMessage<GeoPoint>(NULL);
  }

  GeoPoint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GeoPoint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GeoPoint& from);
  void MergeFrom(const GeoPoint& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeoPoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float latitude = 1;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 1;
  float latitude() const;
  void set_latitude(float value);

  // float longitude = 2;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 2;
  float longitude() const;
  void set_longitude(float value);

  // @@protoc_insertion_point(class_scope:ColmnarDB.Types.GeoPoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float latitude_;
  float longitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Types_2fComplexPolygon_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComplexPolygon

// repeated .ColmnarDB.Types.Polygon polygons = 1;
inline int ComplexPolygon::polygons_size() const {
  return polygons_.size();
}
inline void ComplexPolygon::clear_polygons() {
  polygons_.Clear();
}
inline ::ColmnarDB::Types::Polygon* ComplexPolygon::mutable_polygons(int index) {
  // @@protoc_insertion_point(field_mutable:ColmnarDB.Types.ComplexPolygon.polygons)
  return polygons_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::Polygon >*
ComplexPolygon::mutable_polygons() {
  // @@protoc_insertion_point(field_mutable_list:ColmnarDB.Types.ComplexPolygon.polygons)
  return &polygons_;
}
inline const ::ColmnarDB::Types::Polygon& ComplexPolygon::polygons(int index) const {
  // @@protoc_insertion_point(field_get:ColmnarDB.Types.ComplexPolygon.polygons)
  return polygons_.Get(index);
}
inline ::ColmnarDB::Types::Polygon* ComplexPolygon::add_polygons() {
  // @@protoc_insertion_point(field_add:ColmnarDB.Types.ComplexPolygon.polygons)
  return polygons_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::Polygon >&
ComplexPolygon::polygons() const {
  // @@protoc_insertion_point(field_list:ColmnarDB.Types.ComplexPolygon.polygons)
  return polygons_;
}

// -------------------------------------------------------------------

// Polygon

// repeated .ColmnarDB.Types.GeoPoint geoPoints = 1;
inline int Polygon::geopoints_size() const {
  return geopoints_.size();
}
inline void Polygon::clear_geopoints() {
  geopoints_.Clear();
}
inline ::ColmnarDB::Types::GeoPoint* Polygon::mutable_geopoints(int index) {
  // @@protoc_insertion_point(field_mutable:ColmnarDB.Types.Polygon.geoPoints)
  return geopoints_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::GeoPoint >*
Polygon::mutable_geopoints() {
  // @@protoc_insertion_point(field_mutable_list:ColmnarDB.Types.Polygon.geoPoints)
  return &geopoints_;
}
inline const ::ColmnarDB::Types::GeoPoint& Polygon::geopoints(int index) const {
  // @@protoc_insertion_point(field_get:ColmnarDB.Types.Polygon.geoPoints)
  return geopoints_.Get(index);
}
inline ::ColmnarDB::Types::GeoPoint* Polygon::add_geopoints() {
  // @@protoc_insertion_point(field_add:ColmnarDB.Types.Polygon.geoPoints)
  return geopoints_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColmnarDB::Types::GeoPoint >&
Polygon::geopoints() const {
  // @@protoc_insertion_point(field_list:ColmnarDB.Types.Polygon.geoPoints)
  return geopoints_;
}

// -------------------------------------------------------------------

// GeoPoint

// float latitude = 1;
inline void GeoPoint::clear_latitude() {
  latitude_ = 0;
}
inline float GeoPoint::latitude() const {
  // @@protoc_insertion_point(field_get:ColmnarDB.Types.GeoPoint.latitude)
  return latitude_;
}
inline void GeoPoint::set_latitude(float value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:ColmnarDB.Types.GeoPoint.latitude)
}

// float longitude = 2;
inline void GeoPoint::clear_longitude() {
  longitude_ = 0;
}
inline float GeoPoint::longitude() const {
  // @@protoc_insertion_point(field_get:ColmnarDB.Types.GeoPoint.longitude)
  return longitude_;
}
inline void GeoPoint::set_longitude(float value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:ColmnarDB.Types.GeoPoint.longitude)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Types
}  // namespace ColmnarDB

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Types_2fComplexPolygon_2eproto
