// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types/Point.proto

#ifndef PROTOBUF_INCLUDED_Types_2fPoint_2eproto
#define PROTOBUF_INCLUDED_Types_2fPoint_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ComplexPolygon.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Types_2fPoint_2eproto 

namespace protobuf_Types_2fPoint_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Types_2fPoint_2eproto
namespace ColmnarDB {
namespace Types {
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
}  // namespace Types
}  // namespace ColmnarDB
namespace google {
namespace protobuf {
template<> ::ColmnarDB::Types::Point* Arena::CreateMaybeMessage<::ColmnarDB::Types::Point>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ColmnarDB {
namespace Types {

// ===================================================================

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ColmnarDB.Types.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Point* other);
  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(NULL);
  }

  Point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .ColmnarDB.Types.GeoPoint geoPoint = 1;
  bool has_geopoint() const;
  void clear_geopoint();
  static const int kGeoPointFieldNumber = 1;
  private:
  const ::ColmnarDB::Types::GeoPoint& _internal_geopoint() const;
  public:
  const ::ColmnarDB::Types::GeoPoint& geopoint() const;
  ::ColmnarDB::Types::GeoPoint* release_geopoint();
  ::ColmnarDB::Types::GeoPoint* mutable_geopoint();
  void set_allocated_geopoint(::ColmnarDB::Types::GeoPoint* geopoint);

  // @@protoc_insertion_point(class_scope:ColmnarDB.Types.Point)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::ColmnarDB::Types::GeoPoint* geopoint_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Types_2fPoint_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// .ColmnarDB.Types.GeoPoint geoPoint = 1;
inline bool Point::has_geopoint() const {
  return this != internal_default_instance() && geopoint_ != NULL;
}
inline const ::ColmnarDB::Types::GeoPoint& Point::_internal_geopoint() const {
  return *geopoint_;
}
inline const ::ColmnarDB::Types::GeoPoint& Point::geopoint() const {
  const ::ColmnarDB::Types::GeoPoint* p = geopoint_;
  // @@protoc_insertion_point(field_get:ColmnarDB.Types.Point.geoPoint)
  return p != NULL ? *p : *reinterpret_cast<const ::ColmnarDB::Types::GeoPoint*>(
      &::ColmnarDB::Types::_GeoPoint_default_instance_);
}
inline ::ColmnarDB::Types::GeoPoint* Point::release_geopoint() {
  // @@protoc_insertion_point(field_release:ColmnarDB.Types.Point.geoPoint)
  
  ::ColmnarDB::Types::GeoPoint* temp = geopoint_;
  geopoint_ = NULL;
  return temp;
}
inline ::ColmnarDB::Types::GeoPoint* Point::mutable_geopoint() {
  
  if (geopoint_ == NULL) {
    auto* p = CreateMaybeMessage<::ColmnarDB::Types::GeoPoint>(GetArenaNoVirtual());
    geopoint_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ColmnarDB.Types.Point.geoPoint)
  return geopoint_;
}
inline void Point::set_allocated_geopoint(::ColmnarDB::Types::GeoPoint* geopoint) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(geopoint_);
  }
  if (geopoint) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      geopoint = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, geopoint, submessage_arena);
    }
    
  } else {
    
  }
  geopoint_ = geopoint;
  // @@protoc_insertion_point(field_set_allocated:ColmnarDB.Types.Point.geoPoint)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Types
}  // namespace ColmnarDB

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Types_2fPoint_2eproto
