// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message/InfoMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QikkDB.NetworkClient.Message {

  /// <summary>Holder for reflection information generated from Message/InfoMessage.proto</summary>
  public static partial class InfoMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Message/InfoMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InfoMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlNZXNzYWdlL0luZm9NZXNzYWdlLnByb3RvEhxRaWtrREIuTmV0d29ya0Ns",
            "aWVudC5NZXNzYWdlIuwBCgtJbmZvTWVzc2FnZRJCCgRDb2RlGAEgASgOMjQu",
            "UWlra0RCLk5ldHdvcmtDbGllbnQuTWVzc2FnZS5JbmZvTWVzc2FnZS5TdGF0",
            "dXNDb2RlEg8KB01lc3NhZ2UYAiABKAkihwEKClN0YXR1c0NvZGUSBgoCT0sQ",
            "ABIICgRXQUlUEAESEwoPR0VUX05FWFRfUkVTVUxUEAYSDwoLUVVFUllfRVJS",
            "T1IQAhIQCgxJTVBPUlRfRVJST1IQAxISCg5DT05OX0VTVEFCTElTSBAEEgwK",
            "CENPTk5fRU5EEAUSDQoJSEVBUlRCRUFUEAdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QikkDB.NetworkClient.Message.InfoMessage), global::QikkDB.NetworkClient.Message.InfoMessage.Parser, new[]{ "Code", "Message" }, null, new[]{ typeof(global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class InfoMessage : pb::IMessage<InfoMessage> {
    private static readonly pb::MessageParser<InfoMessage> _parser = new pb::MessageParser<InfoMessage>(() => new InfoMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InfoMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QikkDB.NetworkClient.Message.InfoMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InfoMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InfoMessage(InfoMessage other) : this() {
      code_ = other.code_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InfoMessage Clone() {
      return new InfoMessage(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode code_ = global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InfoMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InfoMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode.Ok) hash ^= Code.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InfoMessage other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode.Ok) {
        Code = other.Code;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::QikkDB.NetworkClient.Message.InfoMessage.Types.StatusCode) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the InfoMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum StatusCode {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("WAIT")] Wait = 1,
        [pbr::OriginalName("GET_NEXT_RESULT")] GetNextResult = 6,
        [pbr::OriginalName("QUERY_ERROR")] QueryError = 2,
        [pbr::OriginalName("IMPORT_ERROR")] ImportError = 3,
        [pbr::OriginalName("CONN_ESTABLISH")] ConnEstablish = 4,
        [pbr::OriginalName("CONN_END")] ConnEnd = 5,
        [pbr::OriginalName("HEARTBEAT")] Heartbeat = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
