# db settings
UsingGPU: true
Dir: ../dropdbase
DatabaseDir: ../databases
BlockSize: 262144
BlockCount: 1024
GroupByBuckets: 65536

#network settings
ListenIP: 127.0.0.1
ListenPort: 12345
Timeout: 5000
